// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trzaeinxlytyqxptkuyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyemFlaW54bHl0eXF4cHRrdXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4OTU3OTcsImV4cCI6MjA0OTQ3MTc5N30.RSh50RC3Vc29U0Xrxn_qDQgeUtH2sEi8JhGIdo1F7jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const handleSupabaseError = (error: any) => {
  console.error('Supabase error:', error);
  
  if (error.message === 'Failed to fetch') {
    return new Error('Unable to connect to the server. Please check your internet connection and try again.');
  }
  
  if (error.message?.includes('Invalid API key')) {
    console.error('API Key error:', { 
      url: SUPABASE_URL,
      keyLength: SUPABASE_PUBLISHABLE_KEY.length,
      error 
    });
    return new Error('Authentication error. Please check API configuration.');
  }
  
  return new Error(error.message || 'An error occurred with the database operation');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'supabase.auth.token',
  },
  global: {
    headers: {
      'x-application-name': 'lovable-dashboard',
    }
  }
});